=== Dwaligon/backrest/doc/xml/dtd/doc.dtd
<!ELEMENT doc ((intro, changelog)|(config, operation)|(variable-list?, cleanup?, section+))>
    <!ATTLIST doc title CDATA "">
    <!ATTLIST doc subtitle CDATA "">
    <!ATTLIST doc toc CDATA "y">

<!ELEMENT intro (text)>

<!ELEMENT operation (text?, operation-general, command-list)>
    <!ATTLIST operation title CDATA #REQUIRED>

<!ELEMENT operation-general (option-list)>
    <!ATTLIST operation-general title CDATA #REQUIRED>

<!ELEMENT command-list (text?, command+)>
    <!ATTLIST command-list title CDATA #REQUIRED>

<!ELEMENT command (summary, text, option-list?, command-example-list)>
    <!ATTLIST command id CDATA #REQUIRED>
    <!ATTLIST command name CDATA #REQUIRED>

<!ELEMENT command-example-list (text?, command-example+)>
    <!ATTLIST command-example-list title CDATA "Examples">

<!ELEMENT command-example (text)>
    <!ATTLIST command-example title CDATA "Example">

<!ELEMENT option-list (option+)>

<!ELEMENT option (summary, text, example)>
    <!ATTLIST option id CDATA #REQUIRED>
    <!ATTLIST option name CDATA #REQUIRED>

<!ELEMENT config (text, config-section-list)>
    <!ATTLIST config title CDATA #REQUIRED>

<!ELEMENT config-example (text)>
    <!ATTLIST config-example title CDATA #REQUIRED>

<!ELEMENT config-section-list (text?, config-section+)>
    <!ATTLIST config-section-list title CDATA #REQUIRED>

<!ELEMENT config-section (text, config-key-list?)>
    <!ATTLIST config-section id CDATA #REQUIRED>
    <!ATTLIST config-section name CDATA #REQUIRED>

<!ELEMENT config-key-list (config-key+)>

<!ELEMENT config-key (summary, text, default?, allow?, example)>
    <!ATTLIST config-key id CDATA #REQUIRED>
    <!ATTLIST config-key name CDATA #REQUIRED>

<!ELEMENT execute-list (title, execute+)>
    <!ATTLIST execute-list host CDATA #REQUIRED>
<!ELEMENT execute (exe-cmd, exe-user?,  exe-var?, exe-retry?, exe-output?, exe-no-show?, exe-highlight?, exe-skip?,
                   exe-err-expect?, exe-err-suppress?, exe-err-suppress-stderr?)>
<!ELEMENT exe-cmd (#PCDATA)>
<!ELEMENT exe-user (#PCDATA)>
<!ELEMENT exe-highlight (#PCDATA)>
<!ELEMENT exe-var (#PCDATA)>
<!ELEMENT exe-output EMPTY>
<!ELEMENT exe-skip EMPTY>
<!ELEMENT exe-no-show EMPTY>
<!ELEMENT exe-retry EMPTY>
<!ELEMENT exe-err-expect (#PCDATA)>
<!ELEMENT exe-err-suppress EMPTY>
<!ELEMENT exe-err-suppress-stderr EMPTY>

<!ELEMENT cleanup (execute+)>

<!ELEMENT variable-list (variable+)>
<!ELEMENT variable (variable-name, variable-value)>
<!ELEMENT variable-name (#PCDATA)>
<!ELEMENT variable-value (#PCDATA)>

<!ELEMENT backrest-config (title, backrest-config-option+)>
    <!ATTLIST backrest-config host CDATA #REQUIRED>
    <!ATTLIST backrest-config owner CDATA "">
    <!ATTLIST backrest-config show CDATA "">
    <!ATTLIST backrest-config file CDATA #REQUIRED>
<!ELEMENT backrest-config-option (backrest-config-option-section?, backrest-config-option-key, backrest-config-option-value?)>
<!ELEMENT backrest-config-option-section (#PCDATA)>
<!ELEMENT backrest-config-option-key (#PCDATA)>
<!ELEMENT backrest-config-option-value (#PCDATA)>

<!ELEMENT postgres-config (title, postgres-config-option+)>
    <!ATTLIST postgres-config host CDATA #REQUIRED>
    <!ATTLIST postgres-config file CDATA #REQUIRED>
<!ELEMENT postgres-config-option (#PCDATA)>
    <!ATTLIST postgres-config-option key CDATA #REQUIRED>

<!ELEMENT option-description EMPTY>
    <!ATTLIST option-description key CDATA #REQUIRED>

<!ELEMENT section (title,
                   ((p|table|host-add|execute-list|backrest-config|postgres-config|option-description|code-block)+|
                   (p*, section+)|p*))>
    <!ATTLIST section id CDATA #REQUIRED>
<!ELEMENT title (#PCDATA|b|i|bi|ul|ol|id|code|file|path|cmd|param|setting|exe|backrest|postgres|br-option|br-setting|
                 pg-option|pg-setting|link|user)*>

<!ELEMENT default (#PCDATA)>
<!ELEMENT allow (#PCDATA)>
<!ELEMENT example (#PCDATA)>

<!ELEMENT changelog (text?, changelog-release+)>

<!ELEMENT changelog-release (text?, release-feature-bullet-list)>
    <!ATTLIST changelog-release date CDATA #REQUIRED>
    <!ATTLIST changelog-release version CDATA #REQUIRED>
    <!ATTLIST changelog-release title CDATA #REQUIRED>

<!ELEMENT release-feature-bullet-list (release-feature+)>

<!ELEMENT release-feature (text)>

<!ELEMENT contribute (text)>
    <!ATTLIST contribute title CDATA #REQUIRED>

<!ELEMENT recognition (text)>
    <!ATTLIST recognition title CDATA #REQUIRED>

<!ELEMENT support (text)>
    <!ATTLIST support title CDATA #REQUIRED>

<!-- Host elements -->
<!ELEMENT host-add (execute*)>
    <!ATTLIST host-add name CDATA #REQUIRED>
    <!ATTLIST host-add user CDATA #REQUIRED>
    <!ATTLIST host-add image CDATA #REQUIRED>
    <!ATTLIST host-add os CDATA "">
    <!ATTLIST host-add mount CDATA "">

<!-- Table elements -->
<!ELEMENT table (title?, table-header, table-data)>

<!ELEMENT table-header (table-column+)>
    <!ATTLIST table-header width CDATA "">
<!ELEMENT table-column (#PCDATA|quote|b|i|id|code|file|path|cmd|param|setting|exe|backrest|postgres|br-option|
                        br-setting|pg-option|pg-setting|link|user)*>
    <!ATTLIST table-column align CDATA "">
    <!ATTLIST table-column fill CDATA "">

<!ELEMENT table-data (table-row+)>
<!ELEMENT table-row (table-cell+)>
<!ELEMENT table-cell (#PCDATA|quote|b|i|ul|ol|id|code|code-block|file|path|cmd|param|setting|exe|backrest|postgres|br-option|
                      br-setting|pg-option|pg-setting|link|user)*>

<!-- Formatted elements -->
<!ELEMENT summary (#PCDATA|quote|b|i|ul|ol|id|code|code-block|file|path|cmd|param|setting|exe|backrest|postgres|br-option|
                   br-setting|pg-option|pg-setting|link|user)*>
<!ELEMENT p (#PCDATA|quote|b|i|ul|ol|id|code|code-block|file|path|cmd|param|setting|exe|backrest|postgres|br-option|br-setting|
             pg-option|pg-setting|link|user)*>
<!ELEMENT text (#PCDATA|quote|b|i|ul|ol|id|code|code-block|file|path|cmd|param|setting|exe|backrest|postgres|br-option|
                br-setting|pg-option|pg-setting|link|user)*>
<!ELEMENT i (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT ul (li+)>
<!ELEMENT ol (li+)>
<!ELEMENT li (#PCDATA|quote|b|i|ul|ol|id|code|code-block|file|path|cmd|param|setting|exe|backrest|postgres|br-option|br-setting|
              pg-option|pg-setting|link|user)*>
<!ELEMENT id (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT code-block (#PCDATA|exe)*>
    <!ATTLIST code-block title CDATA #REQUIRED>

<!ELEMENT file (#PCDATA)>
<!ELEMENT path (#PCDATA)>
<!ELEMENT cmd (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT quote (#PCDATA)>
<!ELEMENT param (#PCDATA)>
<!ELEMENT setting (#PCDATA)>
<!ELEMENT br-option (#PCDATA)>
<!ELEMENT br-setting (#PCDATA)>
<!ELEMENT pg-option (#PCDATA)>
<!ELEMENT pg-setting (#PCDATA)>
<!ELEMENT exe EMPTY>
<!ELEMENT backrest EMPTY>
<!ELEMENT postgres EMPTY>
<!ELEMENT link (#PCDATA)>
    <!ATTLIST link url CDATA "">
    <!ATTLIST link page CDATA "">

=== Dwaligon/backrest/doc/doc/xml/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE doc SYSTEM "doc.dtd">
<doc subtitle="Automated Documentation Made Simple" toc="n">
    <variable-list>
        <!-- Variables used by the rest of the script -->
        <variable key="github-url-base">https://github.com/pgmasters/backrest</variable>
        <variable key="github-url-master">{[github-url-base]}/blob/master</variable>
        <variable key="github-url-issues">{[github-url-base]}/issues</variable>
        <variable key="github-url-change-log">{[github-url-master]}/CHANGELOG.md</variable>
        <variable key="github-url-license">{[github-url-master]}/LICENSE</variable>

        <variable key="backrest-url-base">http://www.pgbackrest.org</variable>
        <variable key="backrest-page-user-guide">user-guide.html</variable>
        <variable key="backrest-page-configuration">configuration.html</variable>
        <variable key="backrest-page-command">command.html</variable>
    </variable-list>

    <section id="introduction">
        <title>Introduction</title>

        <p>It's simple - so simple!</p>
    </section>
</doc>
